.\"                                      Hey, EMACS: -*- nroff -*-
.TH TTMKFDIR 1x "January 30, 2000"
.SH NAME
ttmkfdir \- an utility for creating fonts.scale for TT fonts
.SH SYNOPSIS
.B ttmkfdir
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the \fBttmkfdir\fP command. It was
written for the Debian GNU/Linux and PLD Linux distributions because
the original program does not have a manual page.
.PP
\fBttmkfdir\fP is a program for creating the \fIfonts.scale\fP files
for TrueType fonts.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-h\fR, \fB\-\-help\fR
Shows summary of options.
.TP
\fB\-d\fR, \fB\-\-font\-dir\fR=\fI<directory>\fR
scan directory <directory> for TrueType font files (default is the
current directory)
.TP
\fB\-o\fR, \fB\-\-output\fR=\fI<filename>\fR
write output to file named <filename> (default is standard output)
.TP
\fB\-f\fR, \fB\-\-default\-foundry\fR=\fI<foundry>\fR
use <foundry> name for unknown font vendors (default is 'misc')
.TP
\fB\-e\fR, \fB\-\-encoding\fR=\fI<path>\fR
name of the encoding directory file, default is "encodings.dir"
.TP
\fB\-m\fR, \fB\-\-max\-missing\fR=\fI<number>\fR
maximal number of missing characters per encoding (default is 5)
.TP
\fB\-c\fR, \fB\-\-completeness\fR
use less strict completeness tests for encoding tables
.TP
\fB\-p\fR, \fB\-\-panose\fR
use panose information
.TP
\fB\-a\fR, \fB\-\-max\-missing\-percentage\fR=\fI<number>\fR
max percentage number of missing characters per encodings (default is 2)
.TP
\fB\-x\fR, \fB\-\-additional\-entries\fR=\fI<number>\fR
generate additional TTCaps (1), or FreeType (2) (default is 0)
.SH AUTHOR
Upstream author is Joerg Pomnitz <pommnitz@darmstadt.gmd.de>. This
manual page was written by Miros/law L. Baran <baran@debian.org>, for
the Debian GNU/Linux system (but may be used by others). Updated for
ttmkfdir2 by PLD Team.
